/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface MerkleProofInterface extends utils.Interface {
  contractName: "MerkleProof";
  functions: {
    "buildMerkleTree(string[])": FunctionFragment;
    "getMerkleRoot()": FunctionFragment;
    "getTotalMerkleTree()": FunctionFragment;
    "hashes(uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "buildMerkleTree",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getMerkleRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalMerkleTree",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hashes",
    values: [BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "buildMerkleTree",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalMerkleTree",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hashes", data: BytesLike): Result;

  events: {};
}

export interface MerkleProof extends BaseContract {
  contractName: "MerkleProof";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: MerkleProofInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    buildMerkleTree(
      data: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getMerkleRoot(overrides?: CallOverrides): Promise<[string]>;

    getTotalMerkleTree(overrides?: CallOverrides): Promise<[string[]]>;

    hashes(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;
  };

  buildMerkleTree(
    data: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getMerkleRoot(overrides?: CallOverrides): Promise<string>;

  getTotalMerkleTree(overrides?: CallOverrides): Promise<string[]>;

  hashes(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  callStatic: {
    buildMerkleTree(data: string[], overrides?: CallOverrides): Promise<void>;

    getMerkleRoot(overrides?: CallOverrides): Promise<string>;

    getTotalMerkleTree(overrides?: CallOverrides): Promise<string[]>;

    hashes(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    buildMerkleTree(
      data: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getMerkleRoot(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalMerkleTree(overrides?: CallOverrides): Promise<BigNumber>;

    hashes(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    buildMerkleTree(
      data: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getMerkleRoot(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTotalMerkleTree(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
