/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface TestMerkleProofInterface extends utils.Interface {
  contractName: "TestMerkleProof";
  functions: {
    "buildTestMerkleTree(string[])": FunctionFragment;
    "getStringHash(string)": FunctionFragment;
    "getTestMerkleRoot()": FunctionFragment;
    "getTotalTestMerkleTree()": FunctionFragment;
    "hashes(uint256)": FunctionFragment;
    "verifyData(string,uint256)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "buildTestMerkleTree",
    values: [string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getStringHash",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getTestMerkleRoot",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTotalTestMerkleTree",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "hashes",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyData",
    values: [string, BigNumberish]
  ): string;

  decodeFunctionResult(
    functionFragment: "buildTestMerkleTree",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStringHash",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTestMerkleRoot",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getTotalTestMerkleTree",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hashes", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "verifyData", data: BytesLike): Result;

  events: {};
}

export interface TestMerkleProof extends BaseContract {
  contractName: "TestMerkleProof";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TestMerkleProofInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    buildTestMerkleTree(
      data: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    getStringHash(data: string, overrides?: CallOverrides): Promise<[string]>;

    getTestMerkleRoot(overrides?: CallOverrides): Promise<[string]>;

    getTotalTestMerkleTree(overrides?: CallOverrides): Promise<[string[]]>;

    hashes(arg0: BigNumberish, overrides?: CallOverrides): Promise<[string]>;

    verifyData(
      data: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;
  };

  buildTestMerkleTree(
    data: string[],
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  getStringHash(data: string, overrides?: CallOverrides): Promise<string>;

  getTestMerkleRoot(overrides?: CallOverrides): Promise<string>;

  getTotalTestMerkleTree(overrides?: CallOverrides): Promise<string[]>;

  hashes(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

  verifyData(
    data: string,
    index: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  callStatic: {
    buildTestMerkleTree(
      data: string[],
      overrides?: CallOverrides
    ): Promise<void>;

    getStringHash(data: string, overrides?: CallOverrides): Promise<string>;

    getTestMerkleRoot(overrides?: CallOverrides): Promise<string>;

    getTotalTestMerkleTree(overrides?: CallOverrides): Promise<string[]>;

    hashes(arg0: BigNumberish, overrides?: CallOverrides): Promise<string>;

    verifyData(
      data: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;
  };

  filters: {};

  estimateGas: {
    buildTestMerkleTree(
      data: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    getStringHash(data: string, overrides?: CallOverrides): Promise<BigNumber>;

    getTestMerkleRoot(overrides?: CallOverrides): Promise<BigNumber>;

    getTotalTestMerkleTree(overrides?: CallOverrides): Promise<BigNumber>;

    hashes(arg0: BigNumberish, overrides?: CallOverrides): Promise<BigNumber>;

    verifyData(
      data: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buildTestMerkleTree(
      data: string[],
      overrides?: Overrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    getStringHash(
      data: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getTestMerkleRoot(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getTotalTestMerkleTree(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    hashes(
      arg0: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    verifyData(
      data: string,
      index: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;
  };
}
